use_frameworks!

target 'SafewayWalletPod_Example' do
  pod 'SafewayWalletPod', :path => 'https://github.com/SatheeshKumar1206/SafewayWalletPod.git
'

  target 'SafewayWalletPod_Tests' do
    inherit! :search_paths

    
  end
end
